In [4]:
# importing pandas as pd
import pandas as pd
from tabulate import tabulate

# read an excel file and convert 
# into a dataframe object
df = pd.read_csv("RQNew_Mirantis.csv")
# show the dataframe
df
#print("****")
#print(df2)
#from IPython.display import display, HTML

#with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
 #   print(df2)
#print(tabulate(df, headers='keys', tablefmt='psql'))

,repo_name,first_commit_date,last_commit_date,#months_between_commits,#total_iac_changes,average_iac_change_rate
0,fuel-plugin-swift,2015-07-30 12:59:47+00:00,2015-07-14 10:22:21+00:00,1,14,14.00
1,solar-resources,2016-02-12 10:52:21+00:00,2015-03-27 22:54:19+00:00,12,733,61.08
2,fuel-plugin-celebrer,2016-01-27 00:02:30+00:00,2015-12-22 12:35:54+00:00,2,39,19.50
3,puppet-deployapp,2015-07-29 18:08:23+00:00,2015-07-29 18:05:24+00:00,1,10,10.00
4,puppet-foreman_proxy,2015-07-30 17:04:00+00:00,2015-07-27 13:47:57+00:00,1,24,24.00
5,pmlc_keystone,2015-07-28 20:57:38+00:00,2015-07-27 13:43:47+00:00,1,9,9.00
6,pmlc_neutron,2015-07-30 16:39:21+00:00,2015-07-27 13:43:32+00:00,1,22,22.00
7,pmlc_cinder,2015-07-27 16:55:08+00:00,2015-07-27 13:43:18+00:00,1,6,6.00
8,pmlc_nova,2015-07-30 16:37:35+00:00,2015-07-27 13:43:02+00:00,1,21,21.00
9,roles,2015-07-28 02:20:12+00:00,2015-07-27 13:20:54+00:00,1,30,30.00
10,profiles,2015-07-28 02:21:10+00:00,2015-07-27 13:20:35+00:00,1,41,41.00
11,solar,2015-12-11 09:06:55+00:00,2015-03-27 22:54:19+00:00,10,922,92.20
12,puppet-sudo,2015-05-15 05:41:51+00:00,2015-05-15 04:47:37+00:00,1,9,9.00